### ISSUE TITLE
Example indexing stops at 200 chunks (in Kerchunk file)

### ISSUE THREAD

**Issue by agstephens** [cedadev/kerchunk-tools#11]
We have an example test when generating kerchunk files that causes an error...

```
import intake
import intake_esm

uri = "intake-catalogs/ceda-cmip6-files.json"
cat = intake.open_esm_datastore(uri)

cat_subset = cat.search(
    experiment_id=["historical", "ssp585"],
    table_id="Oyr",
    variable_id="o2",
    grid_label="gn",
)

dset_dict = cat_subset.to_dataset_dict(
    xarray_open_kwargs={"decode_times": False, "use_cftime": True}
)


ds2 = dset_dict["CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest"]

float(ds2.o2[:,0,0,0])
```

We expect the `xarray Dataset` to have this time coordinate:

```
>>> len(ds2.coords["time"])
263

```

But when we slice it we get:

```
  File "/home/users/astephen/miniconda/envs/kerchunk-tools/lib/python3.9/site-packages/fsspec/implementations/reference.py", line 216, in _cat_common
    part = self.references[path]
KeyError: 'o2/200.0.0.0'
```

This suggests that the structure of the indexes only goes up to 200 time steps. This can be checked with:

```
>>> fpath = "/home/users/astephen/kerchunk-intake/sandbox/outputs/kc-indexes/files/CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest.json"

>>> import json

>>> d = json.load(open(fpath))

>>> sorted([key for key in d['refs'].keys() if key.startswith('o2') and key.count('.') > 2])
['o2/0.0.0.0', 'o2/1.0.0.0', 'o2/10.0.0.0', 'o2/100.0.0.0', 'o2/101.0.0.0', 'o2/102.0.0.0', 'o2/103.0.0.0', 'o2/104.0.0.0', 'o2/105.0.0.0', 'o2/106.0.0.0', 'o2/107.0.0.0', 'o2/108.0.0.0', 'o2/109.0.0.0', 'o2/11.0.0.0', 'o2/110.0.0.0', 'o2/111.0.0.0', 'o2/112.0.0.0', 'o2/113.0.0.0', 'o2/114.0.0.0', 'o2/115.0.0.0', 'o2/116.0.0.0', 'o2/117.0.0.0', 'o2/118.0.0.0', 'o2/119.0.0.0', 'o2/12.0.0.0', 'o2/120.0.0.0', 'o2/121.0.0.0', 'o2/122.0.0.0', 'o2/123.0.0.0', 'o2/124.0.0.0', 'o2/125.0.0.0', 'o2/126.0.0.0', 'o2/127.0.0.0', 'o2/128.0.0.0', 'o2/129.0.0.0', 'o2/13.0.0.0', 'o2/130.0.0.0', 'o2/131.0.0.0', 'o2/132.0.0.0', 'o2/133.0.0.0', 'o2/134.0.0.0', 'o2/135.0.0.0', 'o2/136.0.0.0', 'o2/137.0.0.0', 'o2/138.0.0.0', 'o2/139.0.0.0', 'o2/14.0.0.0', 'o2/140.0.0.0', 'o2/141.0.0.0', 'o2/142.0.0.0', 'o2/143.0.0.0', 'o2/144.0.0.0', 'o2/145.0.0.0', 'o2/146.0.0.0', 'o2/147.0.0.0', 'o2/148.0.0.0', 'o2/149.0.0.0', 'o2/15.0.0.0', 'o2/150.0.0.0', 'o2/151.0.0.0', 'o2/152.0.0.0', 'o2/153.0.0.0', 'o2/154.0.0.0', 'o2/155.0.0.0', 'o2/156.0.0.0', 'o2/157.0.0.0', 'o2/158.0.0.0', 'o2/159.0.0.0', 'o2/16.0.0.0', 'o2/160.0.0.0', 'o2/161.0.0.0', 'o2/162.0.0.0', 'o2/163.0.0.0', 'o2/164.0.0.0', 'o2/165.0.0.0', 'o2/166.0.0.0', 'o2/167.0.0.0', 'o2/168.0.0.0', 'o2/169.0.0.0', 'o2/17.0.0.0', 'o2/170.0.0.0', 'o2/171.0.0.0', 'o2/172.0.0.0', 'o2/173.0.0.0', 'o2/174.0.0.0', 'o2/175.0.0.0', 'o2/176.0.0.0', 'o2/177.0.0.0', 'o2/178.0.0.0', 'o2/179.0.0.0', 'o2/18.0.0.0', 'o2/180.0.0.0', 'o2/181.0.0.0', 'o2/182.0.0.0', 'o2/183.0.0.0', 'o2/184.0.0.0', 'o2/185.0.0.0', 'o2/186.0.0.0', 'o2/187.0.0.0', 'o2/188.0.0.0', 'o2/189.0.0.0', 'o2/19.0.0.0', 'o2/190.0.0.0', 'o2/191.0.0.0', 'o2/192.0.0.0', 'o2/193.0.0.0', 'o2/194.0.0.0', 'o2/195.0.0.0', 'o2/196.0.0.0', 'o2/197.0.0.0', 'o2/198.0.0.0', 'o2/199.0.0.0', 'o2/2.0.0.0', 'o2/20.0.0.0', 'o2/21.0.0.0', 'o2/22.0.0.0', 'o2/23.0.0.0', 'o2/24.0.0.0', 'o2/25.0.0.0', 'o2/26.0.0.0', 'o2/27.0.0.0', 'o2/28.0.0.0', 'o2/29.0.0.0', 'o2/3.0.0.0', 'o2/30.0.0.0', 'o2/31.0.0.0', 'o2/32.0.0.0', 'o2/33.0.0.0', 'o2/34.0.0.0', 'o2/35.0.0.0', 'o2/36.0.0.0', 'o2/37.0.0.0', 'o2/38.0.0.0', 'o2/39.0.0.0', 'o2/4.0.0.0', 'o2/40.0.0.0', 'o2/41.0.0.0', 'o2/42.0.0.0', 'o2/43.0.0.0', 'o2/44.0.0.0', 'o2/45.0.0.0', 'o2/46.0.0.0', 'o2/47.0.0.0', 'o2/48.0.0.0', 'o2/49.0.0.0', 'o2/5.0.0.0', 'o2/50.0.0.0', 'o2/51.0.0.0', 'o2/52.0.0.0', 'o2/53.0.0.0', 'o2/54.0.0.0', 'o2/55.0.0.0', 'o2/56.0.0.0', 'o2/57.0.0.0', 'o2/58.0.0.0', 'o2/59.0.0.0', 'o2/6.0.0.0', 'o2/60.0.0.0', 'o2/61.0.0.0', 'o2/62.0.0.0', 'o2/63.0.0.0', 'o2/64.0.0.0', 'o2/65.0.0.0', 'o2/66.0.0.0', 'o2/67.0.0.0', 'o2/68.0.0.0', 'o2/69.0.0.0', 'o2/7.0.0.0', 'o2/70.0.0.0', 'o2/71.0.0.0', 'o2/72.0.0.0', 'o2/73.0.0.0', 'o2/74.0.0.0', 'o2/75.0.0.0', 'o2/76.0.0.0', 'o2/77.0.0.0', 'o2/78.0.0.0', 'o2/79.0.0.0', 'o2/8.0.0.0', 'o2/80.0.0.0', 'o2/81.0.0.0', 'o2/82.0.0.0', 'o2/83.0.0.0', 'o2/84.0.0.0', 'o2/85.0.0.0', 'o2/86.0.0.0', 'o2/87.0.0.0', 'o2/88.0.0.0', 'o2/89.0.0.0', 'o2/9.0.0.0', 'o2/90.0.0.0', 'o2/91.0.0.0', 'o2/92.0.0.0', 'o2/93.0.0.0', 'o2/94.0.0.0', 'o2/95.0.0.0', 'o2/96.0.0.0', 'o2/97.0.0.0', 'o2/98.0.0.0', 'o2/99.0.0.0']


>>> sorted([key for key in d['refs'].keys() if key.startswith('time') and 'z' not in key])
['time/0', 'time_bounds/0.0', 'time_bounds/1.0', 'time_bounds/10.0', 'time_bounds/100.0', 'time_bounds/101.0', 'time_bounds/102.0', 'time_bounds/103.0', 'time_bounds/104.0', 'time_bounds/105.0', 'time_bounds/106.0', 'time_bounds/107.0', 'time_bounds/108.0', 'time_bounds/109.0', 'time_bounds/11.0', 'time_bounds/110.0', 'time_bounds/111.0', 'time_bounds/112.0', 'time_bounds/113.0', 'time_bounds/114.0', 'time_bounds/115.0', 'time_bounds/116.0', 'time_bounds/117.0', 'time_bounds/118.0', 'time_bounds/119.0', 'time_bounds/12.0', 'time_bounds/120.0', 'time_bounds/121.0', 'time_bounds/122.0', 'time_bounds/123.0', 'time_bounds/124.0', 'time_bounds/125.0', 'time_bounds/126.0', 'time_bounds/127.0', 'time_bounds/128.0', 'time_bounds/129.0', 'time_bounds/13.0', 'time_bounds/130.0', 'time_bounds/131.0', 'time_bounds/132.0', 'time_bounds/133.0', 'time_bounds/134.0', 'time_bounds/135.0', 'time_bounds/136.0', 'time_bounds/137.0', 'time_bounds/138.0', 'time_bounds/139.0', 'time_bounds/14.0', 'time_bounds/140.0', 'time_bounds/141.0', 'time_bounds/142.0', 'time_bounds/143.0', 'time_bounds/144.0', 'time_bounds/145.0', 'time_bounds/146.0', 'time_bounds/147.0', 'time_bounds/148.0', 'time_bounds/149.0', 'time_bounds/15.0', 'time_bounds/150.0', 'time_bounds/151.0', 'time_bounds/152.0', 'time_bounds/153.0', 'time_bounds/154.0', 'time_bounds/155.0', 'time_bounds/156.0', 'time_bounds/157.0', 'time_bounds/158.0', 'time_bounds/159.0', 'time_bounds/16.0', 'time_bounds/160.0', 'time_bounds/161.0', 'time_bounds/162.0', 'time_bounds/163.0', 'time_bounds/164.0', 'time_bounds/165.0', 'time_bounds/166.0', 'time_bounds/167.0', 'time_bounds/168.0', 'time_bounds/169.0', 'time_bounds/17.0', 'time_bounds/170.0', 'time_bounds/171.0', 'time_bounds/172.0', 'time_bounds/173.0', 'time_bounds/174.0', 'time_bounds/175.0', 'time_bounds/176.0', 'time_bounds/177.0', 'time_bounds/178.0', 'time_bounds/179.0', 'time_bounds/18.0', 'time_bounds/180.0', 'time_bounds/181.0', 'time_bounds/182.0', 'time_bounds/183.0', 'time_bounds/184.0', 'time_bounds/185.0', 'time_bounds/186.0', 'time_bounds/187.0', 'time_bounds/188.0', 'time_bounds/189.0', 'time_bounds/19.0', 'time_bounds/190.0', 'time_bounds/191.0', 'time_bounds/192.0', 'time_bounds/193.0', 'time_bounds/194.0', 'time_bounds/195.0', 'time_bounds/196.0', 'time_bounds/197.0', 'time_bounds/198.0', 'time_bounds/199.0', 'time_bounds/2.0', 'time_bounds/20.0', 'time_bounds/21.0', 'time_bounds/22.0', 'time_bounds/23.0', 'time_bounds/24.0', 'time_bounds/25.0', 'time_bounds/26.0', 'time_bounds/27.0', 'time_bounds/28.0', 'time_bounds/29.0', 'time_bounds/3.0', 'time_bounds/30.0', 'time_bounds/31.0', 'time_bounds/32.0', 'time_bounds/33.0', 'time_bounds/34.0', 'time_bounds/35.0', 'time_bounds/36.0', 'time_bounds/37.0', 'time_bounds/38.0', 'time_bounds/39.0', 'time_bounds/4.0', 'time_bounds/40.0', 'time_bounds/41.0', 'time_bounds/42.0', 'time_bounds/43.0', 'time_bounds/44.0', 'time_bounds/45.0', 'time_bounds/46.0', 'time_bounds/47.0', 'time_bounds/48.0', 'time_bounds/49.0', 'time_bounds/5.0', 'time_bounds/50.0', 'time_bounds/51.0', 'time_bounds/52.0', 'time_bounds/53.0', 'time_bounds/54.0', 'time_bounds/55.0', 'time_bounds/56.0', 'time_bounds/57.0', 'time_bounds/58.0', 'time_bounds/59.0', 'time_bounds/6.0', 'time_bounds/60.0', 'time_bounds/61.0', 'time_bounds/62.0', 'time_bounds/63.0', 'time_bounds/64.0', 'time_bounds/65.0', 'time_bounds/66.0', 'time_bounds/67.0', 'time_bounds/68.0', 'time_bounds/69.0', 'time_bounds/7.0', 'time_bounds/70.0', 'time_bounds/71.0', 'time_bounds/72.0', 'time_bounds/73.0', 'time_bounds/74.0', 'time_bounds/75.0', 'time_bounds/76.0', 'time_bounds/77.0', 'time_bounds/78.0', 'time_bounds/79.0', 'time_bounds/8.0', 'time_bounds/80.0', 'time_bounds/81.0', 'time_bounds/82.0', 'time_bounds/83.0', 'time_bounds/84.0', 'time_bounds/85.0', 'time_bounds/86.0', 'time_bounds/87.0', 'time_bounds/88.0', 'time_bounds/89.0', 'time_bounds/9.0', 'time_bounds/90.0', 'time_bounds/91.0', 'time_bounds/92.0', 'time_bounds/93.0', 'time_bounds/94.0', 'time_bounds/95.0', 'time_bounds/96.0', 'time_bounds/97.0', 'time_bounds/98.0', 'time_bounds/99.0']

```

So, we need to investigate why our indexing process does not fully work.

## How do we create an index file?

```
max_bytes=50000
prefix="outputs/kc-indexes/files"
kc_paths_file=kc-paths.txt

dr="/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest"
dsid=$(echo $dr | sed 's|/badc/cmip6/data/||' | sed 's|/|\.|g')

kc_file="${dsid}.json"
filepaths=${dr}/*.nc

_cmd="kerchunk_tools create -p $prefix -o $kc_file -b $max_bytes $filepaths"
time $_cmd
```

## How do we quickly check if it indexed beyond 200 time points?

```
grep -P "time_bounds/199\." outputs/kc-indexes/files/CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest.json 
```

...gives us a match

```
grep -P "time_bounds/200\." outputs/kc-indexes/files/CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest.json 
```

...does not!

**Is it related to the `max_bytes` argument?**

**Comment by agstephens** [comment]
@Will-Cross1: here is the first thing to try:

Save this to a script: `test-intake-ipsl.py`

```
import intake
import intake_esm

uri = "intake-catalogs/ceda-cmip6-files.json"
cat = intake.open_esm_datastore(uri)

cat_subset = cat.search(
    experiment_id=["historical", "ssp585"],
    table_id="Oyr",
    variable_id="o2",
    grid_label="gn",
)

dset_dict = cat_subset.to_dataset_dict(
    xarray_open_kwargs={"decode_times": False, "use_cftime": True}
)


ds2 = dset_dict["CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest"]

float(ds2.o2[:,0,0,0])
```

Check that it gives an exception when you run:

```
python ./test-intake-ipsl.py
```

It should give an error like:

```
KeyError: 'o2/242.0.0.0'
```

...which indicates that not all the information is making it into the Kerchunk file:

```
outputs/kc-indexes/files/CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp585.r1i1p1f1.Oyr.o2.gn.latest.json
```

So, we want to regenerate that Kerchunk file on its own but trying to use a higher value for `max_bytes` (NOTE: `max_bytes` connects to a setting when you create Kerchunk files that decides how much information is pulled into the Kerchunk JSON description of the file. My guess is that it might need increasing to capture all the time steps). You can do that with:

```
max_bytes=500000  # This is x10 of what we used before
prefix="outputs/kc-indexes/files"
dr=/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest

echo "[INFO] Working on $dr"
echo "[INFO] Found $(ls $dr/*.nc | wc -l) files"

dsid=$(echo $dr | sed 's|/badc/cmip6/data/||' | sed 's|/|\.|g')
kc_file="${dsid}.json"
filepaths=${dr}/*.nc

kerchunk_tools create -p $prefix -o $kc_file -b $max_bytes $filepaths
```

NOTE: The code above is extracted from the script: `make-kc-indexes-files.sh` - but just works for a single kerchunk file.

This should re-generate the Kerchunk file and then you can retest with the script `test-intake-ipsl.py`.

NOTE: you can add the `test-intake-ipsl.py` script to your repo and push it to GitHub - it is a useful reference.

**Comment by Will-Cross1** [comment]
After running the above shell script, this error happens

(kerchunk-tools) [wcross@sci1 kerchunk-intake-sandbox]$ python test-intake-ipsl.py

--> The keys in the returned dictionary of datasets are constructed as follows:
        'project.activity_id.source_id.institution_id.experiment_id.member_id.table_id.variable_id.grid_label.version'
Traceback (most recent call last):████████████████████████████████| 100.00% [20/20 00:05<00:00]
  File "/home/users/wcross/kc-intake/kerchunk-intake-sandbox/test-intake-ipsl.py", line 21, in <module>
    float(ds2.o2[:,0,0,0])
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/common.py", line 156, in __float__
    return float(self.values)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/dataarray.py", line 729, in values
    return self.variable.values
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/variable.py", line 608, in values
    return _as_array_or_item(self._data)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/variable.py", line 314, in _as_array_or_item
    data = np.asarray(data)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/array/core.py", line 1689, in __array__
    x = self.compute()
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/base.py", line 603, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/dask/array/core.py", line 125, in getter
    c = np.asarray(c)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/indexing.py", line 459, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/indexing.py", line 623, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/coding/variables.py", line 72, in __array__
    return self.func(self.array)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/coding/variables.py", line 139, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/core/indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/xarray/backends/zarr.py", line 68, in __getitem__
    return array[key.tuple]
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/core.py", line 788, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/core.py", line 914, in get_basic_selection
    return self._get_basic_selection_nd(selection=selection, out=out,
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/core.py", line 957, in _get_basic_selection_nd
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/core.py", line 1252, in _get_selection
    self._chunk_getitems(lchunk_coords, lchunk_selection, out, lout_selection,
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/core.py", line 1985, in _chunk_getitems
    cdatas = self.chunk_store.getitems(ckeys, on_error="omit")
  File "/apps/jasmin/jaspy/miniconda_envs/jaspy3.10/m3-4.9.2/envs/jaspy3.10-m3-4.9.2-r20220721/lib/python3.10/site-packages/zarr/storage.py", line 1361, in getitems
    results = self.map.getitems(keys_transformed, on_error="omit")
  File "/home/users/wcross/.local/lib/python3.10/site-packages/fsspec/mapping.py", line 93, in getitems
    out = self.fs.cat(keys2, on_error=oe)
  File "/home/users/wcross/.local/lib/python3.10/site-packages/fsspec/implementations/reference.py", line 313, in cat
    urls, starts, ends = zip(*[self._cat_common(p) for p in paths])
  File "/home/users/wcross/.local/lib/python3.10/site-packages/fsspec/implementations/reference.py", line 313, in <listcomp>
    urls, starts, ends = zip(*[self._cat_common(p) for p in paths])
  File "/home/users/wcross/.local/lib/python3.10/site-packages/fsspec/implementations/reference.py", line 216, in _cat_common
    part = self.references[path]
KeyError: 'o2/231.0.0.0'

**Comment by agstephens** [comment]
Detailed plan:
1. Regenerate the kerchunk files for all NC files (in `kerchunk-cache` directory) as aggregated file:
```
max_bytes=500  # This is x10 of what we used before
prefix="outputs/kc-indexes/files"
dr=/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest

echo "[INFO] Working on $dr"
echo "[INFO] Found $(ls $dr/*.nc | wc -l) files"

dsid=$(echo $dr | sed 's|/badc/cmip6/data/||' | sed 's|/|\.|g')
kc_file="${dsid}.json"
filepaths=${dr}/*.nc

kerchunk_tools create -p $prefix -o $kc_file -b $max_bytes -C ./kerchunk-cache $filepaths
```

2. Compare contents of the individual and aggregated JSON files to understand:
- which chunks exist in each individual file (e.g. `o2/0.0.0.0`, `o2/1.0.0.0`, ...) - matching NetCDF contents
- which chunks exist in the aggregated file

**Comment by Will-Cross1** [comment]
seems only `o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2101-2300.nc` exists in the JSON file and `o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2015-2100.nc` isn't mentioned at all

**Comment by agstephens** [comment]
Thanks @Will-Cross1, 

You said:
> seems only o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2101-2300.nc exists in the JSON file and o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2015-2100.nc isn't mentioned at all

Can you reproduce this if you run it again? If so, please can you copy the code here so that I can do the same.

Thanks

**Comment by Will-Cross1** [comment]
using this code I get the same result



```
max_bytes=500  # This is 10x less of what we used before
prefix="outputs/kc-indexes/files/issue-11"
dr=/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest

echo "[INFO] Working on $dr"
echo "[INFO] Found $(ls $dr/*.nc | wc -l) files"

dsid=$(echo $dr | sed 's|/badc/cmip6/data/||' | sed 's|/|\.|g')
kc_file="${dsid}.json"
filepaths=${dr}/*.nc

kerchunk_tools create -p $prefix -o $kc_file -b $max_bytes -C ./kerchunk-cache $filepaths
```

using ctrl f to see where the original files are mentioned

**Comment by agstephens** [comment]
I wonder if it is the `time:units` that is confusing kerchunk:

```
$ ncdump -h /badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest/o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2015-2100.nc > 2015.txt
$ ncdump -h /badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest/o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2101-2300.nc > 2100.txt
$ diff 2015.txt 2100.txt
1c1
< netcdf o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2015-2100 {
---
> netcdf o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2101-2300 {
8c8
<       time = UNLIMITED ; // (86 currently)
---
>       time = UNLIMITED ; // (200 currently)
38,39c38,39
<               time:units = "days since 2015-01-01 00:00:00" ;
<               time:time_origin = "2015-01-01 00:00:00" ;
---
>               time:units = "days since 2101-01-01 00:00:00" ;
>               time:time_origin = "2101-01-01 00:00:00" ;
58c58
<               :name = "/ccc/work/cont003/gencmip6/oboucher/IGCM_OUT/IPSLCM6/PROD/ssp585/CM61-LR-scen-ssp585/CMIP6/OCE/o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_%start_date%-%end_date%" ;
---
>               :name = "/ccc/work/cont003/gencmip6/oboucher/IGCM_OUT/IPSLCM6/PROD/ssp585/CM61-LR-scen-ssp585-ext/CMIP6/OCE/o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_%start_date%-%end_date%" ;
60,61c60,61
<               :creation_date = "2018-12-18T22:14:40Z" ;
<               :tracking_id = "hdl:21.14100/30a00105-3b1b-4a2e-93ae-085346d6bfe5" ;
---
>               :creation_date = "2019-07-30T09:29:13Z" ;
>               :tracking_id = "hdl:21.14100/67b71618-edf7-4b9c-a26f-3834eff452bb" ;
106,107c106,107
<               :CMIP6_CV_version = "cv=6.2.3.5-2-g63b123e" ;
<               :dr2xml_md5sum = "c2dce418e78ca835be1e2ff817c2c403" ;
---
>               :CMIP6_CV_version = "cv=6.2.15.1" ;
>               :dr2xml_md5sum = "c4b76079137f2c3b9298396d121b21c1" ;
$
```

**Comment by agstephens** [comment]
@Will-Cross1: the best way for us to test this is to create two files with the same time units and see if they work. You could do that with:
```
ncdump somefile.nc > somefile.cdl
# Manually edit the somefile.cdl file
ncgen -o somefile2.nc somefile.cdl
```
Then try to create the kerchunk file from two files that have identical `time:units` and `time:origin` attributes.

Note: you will also need to make sure the time data array increases in the second file (i.e. in reference to the units).

**Comment by Will-Cross1** [comment]
`ncks -d olevel,30,40,1 -d y,100,110,1 -d x,100,110,1 -v o2 /badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp585/r1i1p1f1/Oyr/o2/gn/latest/o2_Oyr_IPSL-CM6A-LR_ssp585_r1i1p1f1_gn_2015-2100.nc f1.nc`

gets you a smaller? version of the .nc file to make into cdl file

`ncdump somefile.nc > somefile.cdl`

makes .cdl file

edit it so that the times are the same (the time has numbers and those numbers are the days since the date on the time variable
so changing 2101 to 2015 means 86 years of days to each number in the 2101-2300 file for it to be the same as it was before)

`ncgen -o somefile2.nc somefile.cdl -k 4`

creates edited .nc file (doing `ncdump -k f1_new.nc` will show it as a netCCDF4 file format)

then run the kerchunk file (I ran:

`kerchunk_tools create -p netcdf_creation -o end_file2.json -b 500 /home/users/wcross/kc-intake/kerchunk-intake-sandbox/stuff_test/netcdf_creation/files/f1_newer.nc /home/users/wcross/kc-intake/kerchunk-intake-sandbox/stuff_test/netcdf_creation/files/f2_newer.nc`
)

that should give correct .json file, to check run:

```
$ python
import kerchunk_tools.xarray_wrapper as xr_wrap
index_uri = "netcdf_creation/end_file.json"
ds = xr_wrap.wrap_xr_open(index_uri)
print(ds)
```

**Comment by agstephens** [comment]
We have resolved why this is happening. #27 is our way of trying to overcome the problem.
