### ISSUE TITLE
Add a "map path" option to kerchunk tools

### ISSUE THREAD

**Issue by agstephens** [cedadev/kerchunk-tools#15]
When using the CEDA object store (i.e. s3-quobyte), the paths to files are different to those found under `/badc/` and `/neodc/` in the CEDA archive.

We need a mapping function to manage this, such as that shown in this script:

```
import os
import sys

pth = sys.argv[1]

def map_archive_path(pth):
    realpath = os.path.realpath(pth)
    print(f"[DEBUG] Realpath: {realpath}")
    match = "/".join(realpath.split("/")[3:6])
    suffix = "/".join(realpath.split("/")[6:])
    return f"s3://s3-{match}{suffix}"

if __name__ == "__main__":

    print(map_archive_path(pth))
```

Example usage is:

```
$ python map-path.py /neodc/esacci/ocean_colour/data/v5.0-release/geographic/netcdf/chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc
[DEBUG] Realpath: /datacentre/archvol5/qb139/archive/spot-45772-chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc
s3://s3-qb139/archive/spot-45772-chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc

$ s3cmd ls s3://s3-qb139/archive/spot-45772-chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc
2021-01-18 15:49    201457586  s3://s3-qb139/archive/spot-45772-chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc
```

@Will-Cross1: Please make the following changes to your fork of `kerchunk_tools`:
- [x] Add the `map_archive_path` to the `kerchunk_tools/utils.py` module
- [x] Add a unit test module: `tests/test_utils.py`
- [x] Add some unit tests to the `tests/test_utils.py` module as follows:
  - [x] `test_map_archive_path_success()` 
    - mapping `/neodc/sentinel3a/data/OLCI/L1_EFR/2018/11/28/` to `s3://s3-qb141/archive/spot-9898-28/`
    - mapping `/neodc/esacci/ocean_colour/data/v5.0-release/geographic/netcdf/chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc` to `s3://s3-qb139/archive/spot-45772-chlor_a/monthly/v5.0/2001/ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-200112-fv5.0.nc`
  - [x] `test_map_archive_path_failure()` 
    - assert that the `map_archive_path` raises an exception if you give it a path that doesn't exist, e.g. "/my/nonsense/data"

**Comment by Will-Cross1** [comment]
the original version of the code when ran would miss out a / at the end causing it to fail.

e.g: running python /neodc/sentinel3a/data/OLCI/L1_EFR/2018/11/28/ would return s3://s3-qb141/archive/spot-9898-28 instead of s3://s3-qb141/archive/spot-9898-28/.  (missing the / at the end)

**Comment by agstephens** [comment]
Good stuff @Will-Cross1

**Comment by agstephens** [comment]
Hi @Will-Cross1, are you ready to create a Pull Request for this one? Thanks

**Comment by agstephens** [comment]
Done.
