### ISSUE TITLE
Check `max_bytes` has an effect

### ISSUE THREAD

**Issue by agstephens** [cedadev/kerchunk-tools#20]
@Will-Cross1 Please can you document your experience of `max_bytes` here.

**Comment by Will-Cross1** [comment]
`kerchunk_tools create -p outputs/kc-indexes/files -o CMIP6.CMIP.CSIRO.ACCESS-ESM1-5.historical.r1i1p1f1.Oyr.o2.gn.latest.json -b 50000 /badc/cmip6/data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Oyr/o2/gn/latest/o2_Oyr_ACCESS-ESM1-5_historical_r1i1p1f1_gn_1850-1949.nc` 

creates a file that is 57498 Bytes (`shown by ls -l`) despite having a max bytes of 50000


### max_bytes (-b) = 5000000:
max_bytes in cli.py = 5000000
self.max_bytes in indexer.py = 5000000
same file size at the end (57498 Bytes)


### max_bytes (-b) = 500:
max_bytes in cli.py = 500
self.max_bytes in indexer.py = 500
same file size at the end (57498 Bytes)


### max_bytes (-b) = 0:
max_bytes in cli.py = 0
self.max_bytes in indexer.py = 10000 (default)
same file size at the end (57498 Bytes)


### max_bytes (-b) = -5000:
max_bytes in cli.py = -5000
self.max_bytes in indexer.py = 10000 (default)
same file size at the end (57498 Bytes)
