### ISSUE TITLE
Create new `cli.py` sub-command: map

### ISSUE THREAD

**Issue by agstephens** [cedadev/kerchunk-tools#21]
Remove the 2 `example*` sub-commands in `kerchunk_tools/cli.py`.

Then add a new sub-command with the following features:
- name: `map`
- argument:
  - `filepath`: a file path that will be mapped to an S3 path
- functionality: 
  - call: `kerchunk_tools.utils.map_archive_path(filepath)`
  - print the result (i.e. the mapped filepath) to the terminal
 
Add some tests into:
- `tests/test_cli.py` to demonstrate this works.

**Comment by Will-Cross1** [comment]
if you run `kerchunk_tools map /neodc/sentinel3a/data/OLCI/L1_EFR/2018/11/28/`
then `s3://s3-qb141/archive/spot-9898-28/` is printed to the terminal

**Comment by agstephens** [comment]
@Will-Cross1 That looks right. Please push the change and make a Pull Request and assign to me.
