### ISSUE TITLE
Explore why this kerchunk index is so big

### ISSUE THREAD

**Issue by agstephens** [cedadev/kerchunk-tools#24]
In theory, a kerchunk index file should be relatively small. It should only need to contain data for:
 1. The structure of the file (e.g. attributes about the types of variables, their names and metadata)
 2. Arrays of coordinate variables: such as time, latitude and longitude
 3. Global attributes: i.e. a dictionary of relevant metadata

However, we have an example here that is very big. It appears that _too much_ information is actually being stored in the kerchunk file.

Details:
- Input data file: `s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc`
- Example kerchunk file (created by code below): `s3://kc-index-test/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.json`

Let's look at the file sizes:

```
$ s3cmd ls -l s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc

2022-01-31 16:55    691526117  00000000620A964F0000000061F8149D-1   STANDARD     s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc

$ s3cmd ls -l s3://kc-index-test/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.json

2023-01-23 08:25     32770300  4f862fd43b57dc69f7f65edfbd5a5d33-6   STANDARD     s3://kc-index-test/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.json
```

The kerchunk file was created using:

```
$ kerchunk_tools create -p kc-index-test -o ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.json -b 50000 -c ../s3_config.json s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc
```

@Will-Cross1: Please investigate this as follows:

**NOTE: You have to use the `sci8.jasmin.ac.uk` when read/writing to the S3-Quobyte** (which is what we are doing here)

- [x] Try changing the `-b 50000` option to make it smaller and see if the output file gets any smaller.

Note that you can GET a copy of the S3 file (i.e. copy it to your local file system), with:

```
$ s3cmd get s3://kc-index-test/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.json
```

If the `-b` option does not change anything:
- [x] Look inside the Kerchunk JSON file and see if you can find out what part of the data structure is making up most of the content.

Put all your findings in this GitHub issue.

**Comment by Will-Cross1** [comment]
### **Code Ran:**

`kerchunk_tools create -p outputs/kc-indexes/files -o test_file.json -b 5000000000 -c $HOME/.s3_config.json s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc`

wait a while

`s3cmd ls -l s3://outputs/kc-indexes/files/test_file.json`

2023-01-23 13:39    921630157  8e636a894c0c8b7436ad1359edb3e603-175  STANDARD     s3://outputs/kc-indexes/files/test_file.json


(this was -b 5000000000), seems to be a lot bigger than the others

**Comment by Will-Cross1** [comment]
### **Code Ran (smaller):**

`kerchunk_tools create -p outputs/kc-indexes/files -o test_file2.json -b 500 -c $HOME/.s3_config.json s3://s3-qb208/archive/spot-50582-v3.00/daily/2002/07/04/ESACCI-LST-L3C-LST-MODISA-0.01deg_1DAILY_DAY-20020704000000-fv3.00.nc`

wait a bit

`s3cmd ls -l s3://outputs/kc-indexes/files/test_file2.json`

2023-01-23 13:57       271747  644112c2e514549fccee340568afdab1     STANDARD     s3://outputs/kc-indexes/files/test_file2.json


(this was -b 5000000000), seems to be a lot bigger than the others

**Comment by Will-Cross1** [comment]
what I've noticed is that there are a lot of different versions of things like qual_flag, sataz, solaz, solze, etc. each with a different number at the end like /0.16.21 or /0.17.27 and other numbers starting from /0.0.0

**Comment by agstephens** [comment]
Please can you try out `-b` options for 50, 500, 5000, 50000 and put those numbers into the file name so we can see them easily. Then try using this code to read them:

```
import sys
import os
import warnings
warnings.filterwarnings("ignore")
import json
import numpy as np
import kerchunk_tools.xarray_wrapper as wrap_xr

creds_file = f"{os.environ['HOME']}/.s3_config.json"
s3_config = json.load(open(creds_file))

index_uri = sys.argv[1]
ds = wrap_xr.wrap_xr_open(index_uri, s3_config=s3_config)

lst_uk = ds.lst_unc_loc_atm.sel(time="2002-07-04", lat=slice(50,70), lon=slice(-10, 5))
mx = float(lst_uk.max())
assert 0.603 < mx < 0.605

print("[TEST PASSED] Tested and asserted data looks okay in Xarray!")
```

Run it with each example file (that were created with different `-b` options) - and check whether the assert statement is valid for all.

**Comment by Will-Cross1** [comment]
2023-01-23 15:00       257197  9b959b79563edbdff5f9d464337f0fd5     STANDARD     s3://outputs/test_file_50.json
2023-01-23 15:01       271747  644112c2e514549fccee340568afdab1     STANDARD     s3://outputs/test_file_500.json
2023-01-23 15:02      6148098  13131fadb7aca090b218b55e4bd2d85e-1   STANDARD     s3://outputs/test_file_5000.json
2023-01-23 15:04     32770300  4f862fd43b57dc69f7f65edfbd5a5d33-6   STANDARD     s3://outputs/test_file_50000.json


(kerchunk-tools) [wcross@sci8.jasmin.ac.uk files]$ python file_reader.py s3://outputs/test_file_50.json
[TEST PASSED] Tested and asserted data looks okay in Xarray!
(kerchunk-tools) [wcross@sci8.jasmin.ac.uk files]$ python file_reader.py s3://outputs/test_file_500.json
[TEST PASSED] Tested and asserted data looks okay in Xarray!
(kerchunk-tools) [wcross@sci8.jasmin.ac.uk files]$ python file_reader.py s3://outputs/test_file_5000.json
[TEST PASSED] Tested and asserted data looks okay in Xarray!
(kerchunk-tools) [wcross@sci8.jasmin.ac.uk files]$ python file_reader.py s3://outputs/test_file_50000.json
[TEST PASSED] Tested and asserted data looks okay in Xarray!

**Comment by Will-Cross1** [comment]
50 = 257197
500 = 271747
5000 = 6148098
50000 = 32770300
